/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerbsRouteImport } from './routes/verbs'
import { Route as ImportRouteImport } from './routes/import_'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as AdverbsRouteImport } from './routes/adverbs'
import { Route as AdjectivesRouteImport } from './routes/adjectives'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportVerbsRouteImport } from './routes/import.verbs'
import { Route as ImportAdverbsRouteImport } from './routes/import.adverbs'
import { Route as ImportAdjectivesRouteImport } from './routes/import.adjectives'
import { Route as CampaignRunRouteImport } from './routes/campaign_.run'

const VerbsRoute = VerbsRouteImport.update({
  id: '/verbs',
  path: '/verbs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import_',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const AdverbsRoute = AdverbsRouteImport.update({
  id: '/adverbs',
  path: '/adverbs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjectivesRoute = AdjectivesRouteImport.update({
  id: '/adjectives',
  path: '/adjectives',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportVerbsRoute = ImportVerbsRouteImport.update({
  id: '/import/verbs',
  path: '/import/verbs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportAdverbsRoute = ImportAdverbsRouteImport.update({
  id: '/import/adverbs',
  path: '/import/adverbs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportAdjectivesRoute = ImportAdjectivesRouteImport.update({
  id: '/import/adjectives',
  path: '/import/adjectives',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRunRoute = CampaignRunRouteImport.update({
  id: '/campaign_/run',
  path: '/campaign/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adjectives': typeof AdjectivesRoute
  '/adverbs': typeof AdverbsRoute
  '/campaign': typeof CampaignRoute
  '/import': typeof ImportRoute
  '/verbs': typeof VerbsRoute
  '/campaign/run': typeof CampaignRunRoute
  '/import/adjectives': typeof ImportAdjectivesRoute
  '/import/adverbs': typeof ImportAdverbsRoute
  '/import/verbs': typeof ImportVerbsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adjectives': typeof AdjectivesRoute
  '/adverbs': typeof AdverbsRoute
  '/campaign': typeof CampaignRoute
  '/import': typeof ImportRoute
  '/verbs': typeof VerbsRoute
  '/campaign/run': typeof CampaignRunRoute
  '/import/adjectives': typeof ImportAdjectivesRoute
  '/import/adverbs': typeof ImportAdverbsRoute
  '/import/verbs': typeof ImportVerbsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adjectives': typeof AdjectivesRoute
  '/adverbs': typeof AdverbsRoute
  '/campaign': typeof CampaignRoute
  '/import_': typeof ImportRoute
  '/verbs': typeof VerbsRoute
  '/campaign_/run': typeof CampaignRunRoute
  '/import/adjectives': typeof ImportAdjectivesRoute
  '/import/adverbs': typeof ImportAdverbsRoute
  '/import/verbs': typeof ImportVerbsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adjectives'
    | '/adverbs'
    | '/campaign'
    | '/import'
    | '/verbs'
    | '/campaign/run'
    | '/import/adjectives'
    | '/import/adverbs'
    | '/import/verbs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adjectives'
    | '/adverbs'
    | '/campaign'
    | '/import'
    | '/verbs'
    | '/campaign/run'
    | '/import/adjectives'
    | '/import/adverbs'
    | '/import/verbs'
  id:
    | '__root__'
    | '/'
    | '/adjectives'
    | '/adverbs'
    | '/campaign'
    | '/import_'
    | '/verbs'
    | '/campaign_/run'
    | '/import/adjectives'
    | '/import/adverbs'
    | '/import/verbs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdjectivesRoute: typeof AdjectivesRoute
  AdverbsRoute: typeof AdverbsRoute
  CampaignRoute: typeof CampaignRoute
  ImportRoute: typeof ImportRoute
  VerbsRoute: typeof VerbsRoute
  CampaignRunRoute: typeof CampaignRunRoute
  ImportAdjectivesRoute: typeof ImportAdjectivesRoute
  ImportAdverbsRoute: typeof ImportAdverbsRoute
  ImportVerbsRoute: typeof ImportVerbsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verbs': {
      id: '/verbs'
      path: '/verbs'
      fullPath: '/verbs'
      preLoaderRoute: typeof VerbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import_': {
      id: '/import_'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adverbs': {
      id: '/adverbs'
      path: '/adverbs'
      fullPath: '/adverbs'
      preLoaderRoute: typeof AdverbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjectives': {
      id: '/adjectives'
      path: '/adjectives'
      fullPath: '/adjectives'
      preLoaderRoute: typeof AdjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/verbs': {
      id: '/import/verbs'
      path: '/import/verbs'
      fullPath: '/import/verbs'
      preLoaderRoute: typeof ImportVerbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/adverbs': {
      id: '/import/adverbs'
      path: '/import/adverbs'
      fullPath: '/import/adverbs'
      preLoaderRoute: typeof ImportAdverbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/adjectives': {
      id: '/import/adjectives'
      path: '/import/adjectives'
      fullPath: '/import/adjectives'
      preLoaderRoute: typeof ImportAdjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign_/run': {
      id: '/campaign_/run'
      path: '/campaign/run'
      fullPath: '/campaign/run'
      preLoaderRoute: typeof CampaignRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdjectivesRoute: AdjectivesRoute,
  AdverbsRoute: AdverbsRoute,
  CampaignRoute: CampaignRoute,
  ImportRoute: ImportRoute,
  VerbsRoute: VerbsRoute,
  CampaignRunRoute: CampaignRunRoute,
  ImportAdjectivesRoute: ImportAdjectivesRoute,
  ImportAdverbsRoute: ImportAdverbsRoute,
  ImportVerbsRoute: ImportVerbsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
